#!/bin/sh
set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <CHECKPOINT_NAME>"
  exit 1
fi

# Prompt user to confirm
read -p "This will clear your code in app/ and replace it with checkpoint '$CHECKPOINT'. Are you sure? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
fi

CHECKPOINT=$(echo "$1" | tr '[:upper:]' '[:lower:]')
HOME=/Users/kay/Code/sw/curriculum/teaching_content/ai/genai/coding_with_agents_rework_v3
WORKING_FOLDER_NAME=${DEFAULT_FOLDER:-_code}
WORKING_DIR="$HOME/$WORKING_FOLDER_NAME"
CHECKPOINTS_DIR="$HOME/checkpoint"

cd "$WORKING_DIR" || exit 1
git worktree remove -f "$CHECKPOINTS_DIR"

git worktree add "$CHECKPOINTS_DIR" "checkpoint-$CHECKPOINT"
rm -rf app
cp -a "$CHECKPOINTS_DIR/app" app
git worktree remove --force "$CHECKPOINTS_DIR"
